// <auto-generated/>
// Polyfill for record types on netstandard2.1
// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Polyfill for the IsExternalInit type required by record types on netstandard2.1.
    /// </summary>
    internal static class IsExternalInit
    {
    }
}
